### ISSUE TITLE
Fix increment checks for each PR

### ISSUE THREAD

**Issue by 14113** [banyan/auto-label#6]
I set up auto-label properly but when I'm testing it on new PR I have +1 check. It means on 5th PR I have 6 auto label checks. Any idea of how this could happen?

<img width="1064" alt="Screenshot 2019-09-13 14 01 16" src="https://user-images.githubusercontent.com/472927/64861169-98fc7680-d62f-11e9-96ef-46005957c769.png">

**Comment by banyan** [comment]
@14113 

sorry for late. Many actions are tied to pull request event. For example, when pull request is labeled or the title or description of pull request is modified, the event would be sent. 
Ref: https://developer.github.com/v3/activity/events/types/#pullrequestevent
I think that's why it happens. does this make sense for you?

**Comment by 14113** [comment]
Maybe you are right. Thanks for the help.
